config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'tasks', to: 'tasks#index'
  get 'tasks/new', to: 'tasks#new', as: :create_task
  post 'tasks', to: 'tasks#create'
  get 'tasks/:id', to: 'tasks#show', as: :task
  get 'tasks/:id/edit', to: 'tasks#edit', as: :edit_task
  patch 'tasks/:id', to: 'tasks#update'
  delete 'tasks/:id', to: 'tasks#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to tasks_path
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to tasks_path
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<div class="form">
  <%= form_for(@task) do |f| %>
  <div>
    Modify title <%= f.text_field :title %>
  </div>

  <div>
    Modify Details <%= f.text_field :details %> <br> <br>
  </div>

  <div>
    <%  if @task.new_record? == false %>
      <%= f.check_box :completed, {}, true, false %>
    <% end %>
  </div>

    <%= f.submit %>
  <% end %>
</div>

app/views/tasks/edit.html.erb
<h1> Update a task to do !! </h1>

<%= render 'form', task: @task %>

app/views/tasks/index.html.erb
<h1> Hello </h1>

<h3> <%= link_to "Add a new task", create_task_path %> </h3>


<h2> List of the tasks </h2>

<ul>
  <% @tasks.each do |task| %>
    <li>
      <% if task.completed == true %>
        <i class="fas fa-check-square"></i>
      <% else %>
        <i class="far fa-square"></i>
      <% end  %>
      <strong><%= link_to" #{task.title} :", task_path(task.id)%></strong><%= "#{task.details}."%>
      <%= link_to "<i class='fas fa-trash-alt'></i>".html_safe, task_path(task),
          method: :delete,
          data: { confirm: "Are you sure?" } %>
    </li>
  <% end %>
</ul>

app/views/tasks/new.html.erb
<h2> Add a new task </h2>

<%= render 'form', task: @task %>

app/views/tasks/show.html.erb
<h1> Here is your task : </h1>

<h1> Task : <%= @task.title %>  </h1>

<p> Details: <%= @task.details %></p>

<h2> Have you done it ? <%= @task.completed %></h2>

<%= link_to 'Back', tasks_path %> | <%= link_to 'Edit', edit_task_path %>